// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxmgkmobwybedbdleuer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4bWdrbW9id3liZWRiZGxldWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDQzMTksImV4cCI6MjA2ODY4MDMxOX0.xEQ8czoLukhqZUU5LjtGtZHUyshJEBm2V01mzMK3dSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});